edition = "2024"
enum_discrim_align_threshold = 20
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
struct_field_align_threshold = 20
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
